title: gravitonick
tagline: "Níck"
description: "thoughts on gravity and other topics in theoretical physics"

url: "https://blog.aguiaralves.com"
baseurl: ""

author:
  shortname: Níck
  name: Níckolas de Aguiar Alves
  email: alves.nickolas@ufabc.edu.br
  website: https://aguiaralves.com

logo: /assets/images/favicon.ico
image: /assets/images/social-preview.png
lang: en-US

theme: jekyll-theme-midnight
github:
  is_project_page: false
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-last-modified-at

feed:
  excerpt_only: true

last_modified_at:
  use_git: false

social:
  name: Níckolas de Aguiar Alves
  links: 
    - https://aguiaralves.com
    - https://ui.adsabs.harvard.edu/search/q=author%3A%22de%20Aguiar%20Alves%2C%20N%C3%ADckolas%22&sort=date%20desc%2C%20bibcode%20desc&p_=0
    - http://arxiv.org/a/deaguiaralves_n_1
    - https://figshare.com/authors/N_ckolas_de_Aguiar_Alves/19534192
    - https://github.com/alves-nickolas
    - https://inspirehep.net/authors/2663271
    - http://lattes.cnpq.br/4933609438452718
    - https://scholar.google.com/citations?user=j1hgjXUAAAAJ&hl=en
    - https://www.scopus.com/authid/detail.uri?authorId=58342440400
    - https://stackexchange.com/users/11735692/
    - https://orcid.org/0000-0002-0309-735X
    - https://www.webofscience.com/wos/author/record/LBI-0329-2024

collections:
    
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default